### ISSUE TITLE
Turn applyRochester in MuonProducer.py to "True" by default?

### ISSUE THREAD

**Issue by sdevissc** [cp3-llbb/Framework#128]
...as it seems to work quite well, see:

http://cp3.irmp.ucl.ac.be/~simon/plotForANnew2-4/ll_M_mm_logy.png
http://cp3.irmp.ucl.ac.be/~simon/plotForANnew2-4/ll_Eta_mm_logy.png

**Comment by OlivierBondu** [comment]
:+1: for me

**Comment by blinkseb** [comment]
:-1: for me. It's easy to enable at analysis level, and this brings up a new systematics, so it's better to enable it on purpose to remind you that you're using it :)

**Comment by sdevissc** [comment]
Well...frankly I don't see the reason of not using in by default in our respective analyses: true that this brings a new systematics, but it definitely improves the data/MC agreement... And I hardly see how to have a mumu-based result approved where this correction is not applied.

**Comment by BrieucF** [comment]
I also think that it is better not to turn it on by default as I it does not seem to be a standard in searches aiming for Moriond.

**Comment by sdevissc** [comment]
I don't agree with what is said here, but let's leave it as False by default and in ZA analysis we will consider it as True from our config file.

**Comment by OlivierBondu** [comment]
well I still agree with @sdevissc :smile: : it's good for data/MC agreement, it's coded and does the job it's expected to do, I don't see why we should not use it, recommendations are likely to come given time...

besides, 'standard' has time to evolve in the coming month, if only for the global switch to 76X that would happen some day...

**Comment by vidalm** [comment]
Whether you turn it on by default or not, I don't care. But once Simon and Alex show the plots in the Higgs group, we all have to apply the corrections. No way to escape.

**Comment by sdevissc** [comment]
@vidalm The HiggsExo conveners got our draft of the AN last night, with the corrected plots inside. Now I don't think this is an urgent matter, but at the end, for pre-app/app, that will be certainly required as a minimal quality condition. Now to be honest I don't care setting the condition in the analysis config file instead of in MuonProducer.py, that's equal from the technical point of view.

**Comment by blinkseb** [comment]
I also don't really care where this switch is. We can enable it by default and one can switch off for a given analysis.

However, my main concern is that this flag is hidden, and soon we'll forget that Rochester is applied (and by soon, I mean a couple of months). It's easier to remember if it's explicitly written in the analysis configuration file instead of hidden deep down the framework configuration :smile:

**Comment by sdevissc** [comment]
ok, fine so let's keep it as it is (that is one PR less to do :p ), and just implement this in our respective analyses config file.
