### ISSUE TITLE
Electron RECO SFs

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#156]
There's also RECO SFs for electrons, shouldn't we apply them?

https://indico.cern.ch/event/491499/contribution/2/attachments/1228507/1799787/tnP_EGM_Feb_15.pdf

**Comment by OlivierBondu** [comment]
good question... dunno, I thought usually these got absorbed in ID SF...

**Comment by OlivierBondu** [comment]
Feedback from HWW people: discussion in progress, no decision yet

**Comment by blinkseb** [comment]
It seems like EGamma POG recommends to apply these RECO SFs (see https://hypernews.cern.ch/HyperNews/CMS/get/b2g-selections/291.html)

Something to keep in mind for the future!

**Comment by OlivierBondu** [comment]
fixed in https://github.com/cp3-llbb/Framework/pull/202
