### ISSUE TITLE
Change default branch to CMSSW_7_6_3p

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#172]
I guess it's time to say good bye to CMSSW 7.4.X! Any objections?

**Comment by swertz** [comment]
None here...

**Comment by BrieucF** [comment]
Fine for me ;-)

**Comment by swertz** [comment]
If we do it here we shouldn't forget to do it on the Datasets repo as well, or we're in for a surprise ;)

**Comment by OlivierBondu** [comment]
fine with me :)

**Comment by blinkseb** [comment]
Done :smile:
