### ISSUE TITLE
Question on edmRef in ElectronsProducer

### ISSUE THREAD

**Issue by pieterdavid** [cp3-llbb/Framework#176]
If I understand the documentation at https://twiki.cern.ch/twiki/bin/view/CMSPublic/SWGuideEDMRef correctly, the index used to construct an edmRef should correspond to the index of the object in the container... isn't there a (potential) bug at https://github.com/cp3-llbb/Framework/blob/CMSSW_7_6_3p/src/ElectronsProducer.cc#L31 then that the index does not get incremented in case the electron fails the cut (because of the continue statement)?

**Comment by blinkseb** [comment]
Good catch, thanks a lot! I guess no one is using these cuts, ouf :relieved:

**Comment by pieterdavid** [comment]
I don't think so either (I was checking where I could theoretically insert them, but it's nicer indeed to have them all in one place). Thanks for fixing it so quickly!

**Comment by OlivierBondu** [comment]
ah, it seems github trigger on 'fix', not 'fixes', closing this one !
