### ISSUE TITLE
Updates needed for 8.0.X

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#183]
Just a small list of what we need to update for 8.0.X. Feel free to add more stuff!
- [x] Electrons
  - [x] RECO SFs 
  - [x] effective areas
  - [x] ID
  - [x] ID SFs
  - [x] trigger efficiencies and list in `data/triggers.xml` 
- [x] Muons
  - [x] tracking SF
  - [x] SFs
  - [x] trigger efficiencies and list in `data/triggers.xml`
  - [x] muon momentum scale 
- [ ] Jets
  - [x] update jet IDs (see [the original announcement](https://hypernews.cern.ch/HyperNews/CMS/get/jet-algorithms/399.html) and [this twiki](https://github.com/cp3-llbb/Framework/blob/CMSSW_8_0_6p/interface/Tools.h#L12))
  - [ ] update PU jet ID (see [the twiki](https://twiki.cern.ch/twiki/bin/viewauth/CMS/PileupJetID)) -- Postponed until 2016 rereco
  - [x] B-tagging SFs (we also need to split between light & c/b jets)
  - [x] B-jet regression (see #178)
- [x] PU profile

**Comment by OlivierBondu** [comment]
Closing this issue as this is about Moriond'17 code updates. Issue https://github.com/cp3-llbb/Framework/issues/257 has now been opened to keep track of end-of-the-year state of the art updates!
