### ISSUE TITLE
SF file format extension

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/Framework#198]
Following the discussion at https://github.com/cp3-llbb/Framework/pull/197#issuecomment-249676952 we probably need an extension of the SF files handling, eg to specify which variables are expected in x and y (eg abseta or eta vs pt)

**Comment by blinkseb** [comment]
See possible implementation here:
- https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CondFormats/JetMETObjects/interface/JetResolutionObject.h#L92-L117
- https://github.com/cms-sw/cmssw/blob/CMSSW_8_1_X/CondFormats/JetMETObjects/src/JetResolutionObject.cc#L52-L135
