### ISSUE TITLE
HLT process name

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/Framework#205]
the HLT process name is currently hardcoded to be 'HLT' at https://github.com/cp3-llbb/Framework/blob/f55f525814fc987aacb1a5f3e4af098ad90894d1/interface/HLTProducer.h#L28

however for 80X some samples (typically signal, but not the large backgrounds) have 'HLT2'

so I was thinking of moving this parameter to the `HLTProducer.py` but we would still need a way to go for one or the other on the fly... any ideas ?

**Comment by blinkseb** [comment]
This should be handled in the same way as the process name on data (`PAT` vs `RECO`):
1. Be configurable
2. Be changeable from the command-line
3. Let GridIn change it on the fly if the dataset match a given pattern (hopefully we can find a way to identify such dataset?)

**Comment by blinkseb** [comment]
Just saw that 1. is already fulfilled. It defaults to `HLT` if the parameter is not specified in the configuration file

**Comment by OlivierBondu** [comment]
for 3. there is the string `reHLT` in the dataset name, that should be enough I think
