### ISSUE TITLE
Non-reproducibility ?

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/Framework#4]
Do we have somewhere some random component ? the output trees are different every time I run, see below.

------------------------------------------------------------------------------

Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at 08-Jul-2015 18:59:36.452 CEST
08-Jul-2015 18:59:38 CEST  Closed file file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root

Job done in 2.187s
20 processed events, 9 selected.

------------------------------------------------------------------------------

Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at 08-Jul-2015 19:03:50.937 CEST
08-Jul-2015 19:03:52 CEST  Closed file file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root

Job done in 2.048s
20 processed events, 11 selected.

------------------------------------------------------------------------------

Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at 08-Jul-2015 19:04:46.223 CEST
08-Jul-2015 19:04:47 CEST  Closed file file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root

Job done in 1.99s
20 processed events, 13 selected.

------------------------------------------------------------------------------

Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at 08-Jul-2015 19:06:03.181 CEST
08-Jul-2015 19:06:04 CEST  Closed file file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root

Job done in 1.882s
20 processed events, 8 selected.

**Comment by blinkseb** [comment]
Yes, as illustration purpose, the two muons category is simply a check if a
random number > 0.5, so it's normal here :)

2015-07-08 19:06 GMT+02:00 Olivier <notifications@github.com>:

> Do we have somewhere some random component ? the output trees are
> different every time I run, see below.
> ------------------------------
>
> Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at
> 08-Jul-2015 18:59:36.452 CEST
> 08-Jul-2015 18:59:38 CEST Closed file
> file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root
>
> Job done in 2.187s
> 20 processed events, 9 selected.
> ------------------------------
>
> Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at
> 08-Jul-2015 19:03:50.937 CEST
> 08-Jul-2015 19:03:52 CEST Closed file
> file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root
>
> Job done in 2.048s
> 20 processed events, 11 selected.
> ------------------------------
>
> Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at
> 08-Jul-2015 19:04:46.223 CEST
> 08-Jul-2015 19:04:47 CEST Closed file
> file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root
>
> Job done in 1.99s
> 20 processed events, 13 selected.
> ------------------------------
>
> Begin processing the 1st record. Run 1, Event 6008, LumiSection 25 at
> 08-Jul-2015 19:06:03.181 CEST
> 08-Jul-2015 19:06:04 CEST Closed file
> file:///home/fynu/sbrochet/storage/MINIAODSIM/TTJets_TuneCUETP8M1_13TeV-amcatnloFXFX-pythia8_Asympt25ns_MCRUN2_74_V9_reduced.root
>
> Job done in 1.882s
> 20 processed events, 8 selected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cp3-llbb/Framework/issues/4>.
>



-- 
Sébastien Brochet

**Comment by OlivierBondu** [comment]
:sweat_smile:
