### ISSUE TITLE
Tag first version

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#49]
So, we plan to tag v0 soon (hopefully tomorrow, only FatJetProducer is missing and I'm working on it). How should we name the tags? I propose ``vX.Y.Z``. Do we need to add also the CMSSW version we target inside the tag name? Or maybe it's enough to keep track of which CMSSW we use in the README?

**Comment by swertz** [comment]
Having the CMSSW version in the target might make things easier when looking for a particular version? Something like vX.Y.Z_7XY?

**Comment by blinkseb** [comment]
Yes I guess you're right! But what about numbering when we switch CMSSW release? Should we go back to v1 or just continue the numbering? (ie, ``v1.0.0_74X`` to ``v1.1.0_75X``?)

**Comment by AlexandreMertens** [comment]
I would continue the numbering, otherwise it will become a mess

**Comment by swertz** [comment]
What's the convention of what should go into the three version numbers? I'd say that if the changes that came along the new CMS version are important, increase the major or minor number, and if the only thing that changes is the CMS version (along with specific, detailed changes in the config files for this or that producer), increase the patch number together with the CMS version (ie v1.0.0_74X to v1.0.1_75X)?

**Comment by blinkseb** [comment]
I guess it's effectively a good strategy. I found http://semver.org/ which document the best practices for versionning, so to resume:

 - Major version is updated when we break the API, ie the analyzers won't work anymore without code change
 - Minor version is updated when we add more stuff to the framework without breaking the analyzers.
 - Patch version is updated when we fix bugs.

Si I guess that updating CMSSW should be seen as a minor version update. What do you think?

**Comment by swertz** [comment]
Makes sense. By the way, according to this page's rules, "Build metadata MAY be denoted by appending a plus sign and a series of dot separated identifiers immediately following the patch or pre-release version.". This would leave us with v1.0.0+74X... Then of course, http://tiny.cc/vptc3x...

**Comment by OlivierBondu** [comment]
ok for me with SebB proposal

In principle we are not supposed to update the CMSSW version so often... like the current discussion about the switch to 7 4 12, there are issues and tracking of the switch so in principle people are aware of it in advance and what it changes, it may not be necessary to add it into the tag ?

**Comment by blinkseb** [comment]
Ok so it's the last remaining issue before tagging v0, so what do we decide? :smile_cat:

**Comment by blinkseb** [comment]
Here we go : http://doodle.com/poll/2kvrdg8issnxd47t

**Comment by OlivierBondu** [comment]
Shouldn't we wait for the patch release to fix #38 before tagging ?

**Comment by blinkseb** [comment]
Not sure if it's really useful? We can just bump the tag when we upgrade no?

**Comment by OlivierBondu** [comment]
ok, but then I guess it helps me voting for having the CMSSW release number in the tag !

**Comment by OlivierBondu** [comment]
So: vX.Y.Z+74X ? Any last complaints ?

**Comment by blinkseb** [comment]
Fine with me. So should I proceed to tag``v0.1.0+74X`` ?

2015-09-16 10:52 GMT+02:00 Olivier <notifications@github.com>:

> So: vX.Y.Z+74X ? Any last complaints ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cp3-llbb/Framework/issues/49#issuecomment-140675719>.
>



-- 
Sébastien Brochet

**Comment by OlivierBondu** [comment]
ok for me

**Comment by swertz** [comment]
Ok with me... Is someone testing it before tagging?

**Comment by blinkseb** [comment]
I will :)

2015-09-16 10:59 GMT+02:00 Sébastien Wertz <notifications@github.com>:

> Ok with me... Is someone testing it before tagging?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cp3-llbb/Framework/issues/49#issuecomment-140677112>.
>



-- 
Sébastien Brochet

**Comment by blinkseb** [comment]
And it's done: https://github.com/cp3-llbb/Framework/releases
