### ISSUE TITLE
Update eID to V2

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/Framework#58]
see announcement on the [egamma hn](https://hypernews.cern.ch/HyperNews/CMS/get/egamma/1623.html)

however the [twiki recipes](https://twiki.cern.ch/twiki/bin/view/CMS/EgammaIDRecipesRun2) are in 7.4.12... so we need to wait to fix #38 first

**Comment by blinkseb** [comment]
Closed by #72
