### ISSUE TITLE
Trigger matching

### ISSUE THREAD

**Issue by swertz** [cp3-llbb/Framework#64]
To discuss matching of trigger to objects, to be sure the selected leptons/whatever are those which fired the trigger?

If it's possible already from what is stored by the framework, it's not crystal clear to me... Anyone?

**Comment by BrieucF** [comment]
We started discussing this with Seb B. The matching is currently not possible with what is stored in the framework but all the needed informations are available in miniAOD.

**Comment by blinkseb** [comment]
Closed by #66
