### ISSUE TITLE
Output size

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#83]
The size of the output tree is growing more and more everyday :smile: For the TT analysis, we are for the moment at about 15 kb per event.

I've made a small script which print the size of the tree as well as the size of each branches:

```
******************************************************************************
*Tree    :t         : t                                                      *
*Entries :     1000 : Total =    33.3 MB  File  Size =    14.6 MB  ~ 99.94 % *
*        :          : Tree compression factor =   2.27                       *
******************************************************************************
branch packed_gen_particle_p4                                          6.4 MB    ~43.74 %
branch packed_gen_particle_y                                           1.7 MB    ~11.66 %
branch pruned_gen_particle_p4                                          1.4 MB    ~9.56 %
branch tt_diJets                                                       555 kB    ~3.70 %
branch pruned_gen_particle_y                                           361 kB    ~2.41 %
branch tt_diLepDiJetsMet                                               358 kB    ~2.39 %
branch event_lhe_weights                                               322 kB    ~2.15 %
branch vertex_covariance                                               288 kB    ~1.93 %
branch packed_gen_particle_mothers_index                               248 kB    ~1.65 %
branch packed_gen_particle_pdg_id                                      227 kB    ~1.52 %
branch vertex_position                                                 206 kB    ~1.38 %
branch pruned_gen_particle_mothers_index                               204 kB    ~1.36 %
branch jet_p4                                                          191 kB    ~1.27 %
branch jet_gen_p4                                                      168 kB    ~1.12 %
```

All others branches takes less than 1% of the total size.

As you can see, `packed` gen particles take ~50% of the output size, and, AFAIK, no one is using it. I'm thinking of supporting _transient_ branches : the producer still computes the quantities, but nothing is stored in the tree. Analyses would still be able to access `packed` gen particles, but not afterwards as the branches are not saved.

What do you think?

We can also think of changing the algorithm used to compress the ROOT file. It's `zlib` by default IIRM, but it can be changed to `LZMA` to better compression. However, with better compression efficiency comes slower decompression time. It means that all the plotting will be slower by up to 2x according to some benchmarks.

**Comment by swertz** [comment]
:+1:  for transient branches.

**Comment by OlivierBondu** [comment]
:+1: as well

(could you also push your script ?)

**Comment by blinkseb** [comment]
Script is here :smile: 
https://gist.github.com/blinkseb/9a1c497ec98aafbc57ab
