### ISSUE TITLE
Check if producer exists before casting to reference

### ISSUE THREAD

**Issue by blinkseb** [cp3-llbb/Framework#9]
See https://github.com/cp3-llbb/Framework/blob/master/src/Framework.cc#L178.

If no producer exists, we should throw an exception telling what's going on. A function should also exist in ProducersManager to check if a given producer exists, something like

    bool exists(const std::string& name);

**Comment by OlivierBondu** [comment]
Sure, but maybe if it is about gen information, it should check also if there is some 'data' flag passed instead of crashing ?

**Comment by blinkseb** [comment]
We need to be generic here. What if no 'jets' producer is added and the analyzer try to access it?

**Comment by OlivierBondu** [comment]
agreed, these are in fact two separate issues indeed.
