### ISSUE TITLE
Additional jet info to store for bjet energy regression

### ISSUE THREAD

**Issue by OlivierBondu** [cp3-llbb/Framework#98]
The list of inputs is listed on [this twiki](https://twiki.cern.ch/twiki/bin/view/CMS/HiggsToBBjetEnergyRegression):
- [x] Jet η
- [x] Jet pT
- [x] Jet transverse mass
- [x] JEC
- [x] Neutral hadron energy fraction
- [x] Photon energy fraction
- [x] SecVtxdL, the 3-d flight length of the jet secondary vertex
- [x] SecVtxdeL, Error on the 3-d flight length of the jet secondary vertex
- [x] SecVtxPt, pT of the jet secondary vertex
- [x] SecVtxM, Mass of the jet secondary vertex
- [x] SecVtxNtrk, track multiplicity of the reconstructed secondary vertex
- [x] Soft Lepton pT, transverse momentum of soft lepton candidate in the jet;
- [x] Soft Lepton pTRel, relative transverse momentum of soft lepton candidate in the jet;
- [x] Soft Lepton dR, relative distance in the η-phi space of soft lepton candidate in the jet and the jet;
- [x] Ntot, total number of jet constituents
- [x] pTLeadTrk, transverse momentum of the leading track in the jet
- [x] ρ, the average pT-density of an event.

**Comment by OlivierBondu** [comment]
(I'm still waiting for the code details for the exact implementation)

**Comment by giacomoortona** [comment]
LLR implementation:
https://github.com/LLRCMS/KLUBAnalysis/blob/master/test/skimNtupleInclusive.cpp#L740
(variables definitions: https://github.com/LLRCMS/LLRHiggsTauTau/blob/master/NtupleProducer/plugins/HTauTauNtuplizer.cc)

**Comment by blinkseb** [comment]
Closed by #130
